# OpenAI Models
[gpt-4o]
endpoint = "https://api.openai.com/v1"
model_name = "gpt-4o"
api_key = "${OPENAI_API_KEY}"
logical_name = "GPT-4o"

[gpt-4o-mini]
endpoint = "https://api.openai.com/v1"
model_name = "gpt-4o-mini"
api_key = "${OPENAI_API_KEY}"
logical_name = "GPT-4o Mini"

[gpt-4-turbo]
endpoint = "https://api.openai.com/v1"
model_name = "gpt-4-turbo"
api_key = "${OPENAI_API_KEY}"
logical_name = "GPT-4 Turbo"

[gpt-4.5-preview]
endpoint = "https://api.openai.com/v1"
model_name = "gpt-4.5-preview"
api_key = "${OPENAI_API_KEY}"
logical_name = "GPT-4.5 Preview"

# Anthropic Models
[claude-3-7-sonnet-latest]
endpoint = "https://api.anthropic.com/v1"
model_name = "claude-3-7-sonnet-20240307"
api_key = "${ANTHROPIC_API_KEY}"
logical_name = "Claude 3.7 Sonnet"

# Google Models
[gemini-2.5-pro-preview]
endpoint = "https://generativelanguage.googleapis.com/v1"
model_name = "gemini-2.5-pro-preview-03-25"
api_key = "${GOOGLE_API_KEY}"
logical_name = "Gemini 2.5 Pro Preview"

[gemini-2.0-flash]
endpoint = "https://generativelanguage.googleapis.com/v1"
model_name = "gemini-2.0-flash"
api_key = "${GOOGLE_API_KEY}"
logical_name = "Gemini 2.0 Flash"

[gemini-2.0-flash-lite]
endpoint = "https://generativelanguage.googleapis.com/v1"
model_name = "gemini-2.0-flash-lite"
api_key = "${GOOGLE_API_KEY}"
logical_name = "Gemini 2.0 Flash Lite"